version: '3.8'
services:
  app:
    build: .
    container_name: inventario
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
